name: Tests

on: [ push, pull_request ]

jobs:
  lint-and-ut:
    runs-on: [ ubuntu-18.04 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint
        run: |
          go vet -stdmethods=false $(go list ./...)
          go install mvdan.cc/gofumpt@v0.2.0
          test -z "$(gofumpt -l -extra .)"